"use client";

import { use } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { AuthGuard } from "@/components/auth-guard";
import { Navbar } from "@/components/navbar";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { GenerationProgress } from "@/components/generation/generation-progress";

export default function GeneratingPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: roadmapId } = use(params);
  const searchParams = useSearchParams();
  const jobId = searchParams.get("job");

  return (
    <AuthGuard>
      <div className="min-h-screen">
        <Navbar />
        <main className="container mx-auto max-w-2xl px-4 py-8">
          <PageHeader
            title="Generation Progress"
            description="Your roadmap is being generated by AI"
          />
          <div className="mt-8">
            {jobId ? (
              <GenerationProgress jobId={jobId} roadmapId={roadmapId} />
            ) : (
              <Card>
                <CardHeader>
                  <CardTitle className="text-destructive">Missing Job ID</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-sm text-muted-foreground">
                    No generation job ID was provided. This page requires a job
                    parameter to stream progress.
                  </p>
                  <Button variant="outline" asChild>
                    <Link href="/projects">Back to Projects</Link>
                  </Button>
                </CardContent>
              </Card>
            )}
          </div>
        </main>
      </div>
    </AuthGuard>
  );
}
