name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get release info
      id: release
      run: |
        echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        echo "download_url=https://github.com/robavery/roadmap-notion/releases/download/${GITHUB_REF#refs/tags/}/roadmap-notion-macos" >> $GITHUB_OUTPUT

    - name: Download macOS binary
      run: |
        curl -L ${{ steps.release.outputs.download_url }} -o roadmap-notion-macos

    - name: Calculate SHA256
      id: sha
      run: |
        echo "sha256=$(shasum -a 256 roadmap-notion-macos | cut -d' ' -f1)" >> $GITHUB_OUTPUT

    - name: Update Homebrew formula
      run: |
        sed -i '' 's|url ".*"|url "${{ steps.release.outputs.download_url }}"|' homebrew-formula/roadmap-notion.rb
        sed -i '' 's|sha256 ".*"|sha256 "${{ steps.sha.outputs.sha256 }}"|' homebrew-formula/roadmap-notion.rb
        sed -i '' 's|version ".*"|version "${{ steps.release.outputs.tag_name }}"|' homebrew-formula/roadmap-notion.rb

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add homebrew-formula/roadmap-notion.rb
        git commit -m "Update Homebrew formula for ${{ steps.release.outputs.tag_name }}" || exit 0
        git push